[build]
  functions = "netlify/functions"
  publish ="."

[functions."calculate-points"]
  schedule = "@daily"

[functions."resync-webhook-mints"]
  schedule = "@daily"

[functions."daily-reconciliation"]
  schedule = "0 20 * * *"

[functions."draw-raffle"]
  schedule = "*/5 * * * *"

  [[headers]]
    for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
