[build]
  functions = "netlify/functions"
  publish ="."

[functions."calculate-points"]
  schedule = "@daily"

[functions."resync-webhook-mints"]
  schedule = "@daily"

  [[headers]]
    for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
